services:
  backend:
    build: ./Backend
    container_name: mediashelf_backend
    env_file:
      - ./Backend/.env
    ports:
      - "5000:5000"
    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: mediashelf_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped