services:
  frontend:
    # 'build' tells Docker Compose to build the image from a Dockerfile
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # Give the built image a name
    image: mediashelf-frontend
    container_name: mediashelf_frontend
    ports:
      - "3000:3000" # <-- CHANGE THIS: Map to 3000 in the container
    # REMOVE this volume:
    # volumes:
    #   - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - mediashelf_network
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mediashelf_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - PORT=${BACKEND_PORT}
    depends_on:
      - mongo
    networks:
      - mediashelf_network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mediashelf_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db
    networks:
      - mediashelf_network
    restart: unless-stopped

networks:
  mediashelf_network:
    driver: bridge

volumes:
  mongo_data:


